spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.200.135.43:3306/db_exam?autoReconnect=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Join666!
#    type: com.alibaba.druid.pool.DruidDataSource
#      initialSize: 1
#      minIdle: 3
#      maxActive: 20
#      maxWait: 60000
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 30000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 20
#      filters: stat,wall,slf4j
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      useGlobalDataSourceStat: true
#      server:
#        port:8080
#      servlet:
#        path"/springboot
server:
  port: 8888

mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath*:mapper/*.xml
  configuration:
     cache-enabled: true
    #org.apache.ibatis.logging.stdout.StdOutImpl 控制台打印sql语句方便调试sql语句执行错误
     log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
     mapUnderscoreToCamelCase: true
logging:
  config:
    classpath: log4j2-spring.xml
  level:
      com.example.demo.mapper: DEBUG
#redis:
#  host: 127.0.0.1
#  port: 6379
#  timeout: 5000
#  database: 0
#  password: